---
- name: Remove downloaded files 
  hosts: '{{ local }}' 
  gather_facts: false
  vars:
    directories: ['C:\Users\aluno\Downloads']
  tasks:
    - name: Collect files 
      win_find:
        paths: "{{ directories }}"
        recurse: true 
      register: collected_files

    - name: Remove files
      win_file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ collected_files.files }}"
