---
- name: Testes no lab2
  hosts: lab2 
  tasks:
          #  - name: Instalar as atualizações de segurança
          #    win_updates:
          #      category_names:
          #        - SecurityUpdates
#  - name: install the Win32-OpenSSH service
#    win_chocolatey:
#      name: openssh
#      package_params: /SSHServerFeature
#      state: present
#  - name: Atualizar notepad++
#    win_chocolatey:
#      name: notepadplusplus
#      state: present
- name: Desligar todos os dias às 23h
    community.windows.win_scheduled_task:
      name: Desligar às 23h
      description: Desligar o computador todos os dias às 23h
      actions:
      - path: shutdown.exe
        arguments: /s /f
      triggers:
      - type: daily
        start_boundary: '2022-05-06T23:00:00'
      username: SYSTEM
      run_level: highest
      wake_to_run: yes
      state: present
      enabled: yes
  - name: Remover a(s) tarefa(s) de desligamento antiga(s).
    community.windows.win_scheduled_task:
      name: 
      - desligamento 2300
      - desligamento automático
      - desligamento auto
      state: absent
      executable: cmd
  - name: Copiar o desinstador do Plugin do Adobe Flash para o host remoto
    ansible.windows.win_copy:
      src: uninstall_flash_player.exe
      dest: C:\Windows\temp
