---
- name: Configurar a protecao de tela para exibir a hora.
  hosts: lab3
  remote_user: suporte
  #become: yes
  tasks:
  - community.general.osx_defaults:
      domain: com.apple.screensaver
      host: currentHost
      key: showClock
      type: int
      value: 1
