---

- name: Laboratório 4
  hosts: lab4 
  gather_facts: false
  tasks:
#  - name: Enviar sinal de ligar para 
#    community.windows.win_wakeonlan:
#      mac: 18:A9:FD:EC:DD
#      broadcast: 10.102.227.255
  - name: Instalação de aplicativos via Chocolatey 
    win_chocolatey:
      name: 
      - notepadplusplus
      - vscode
      - googlechrome
      - selenium
      - selenium-chrome-driver
     #- nodejs-lts
      - cypress 
      state: present
  - name: Instalação do NodeJS via instalador MSI
    ansible.windows.win_package:
      path: https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi
      product_id: '{366E8C2E-9CE0-4306-ABBB-E32CC4C328A0}'
      arguments:
      - /install
      - /qn
#  - name: Install all security updates with automatic reboots
#    ansible.windows.win_updates:
#      category_names:
#      - SecurityUpdates
#      reboot: no
#  - name: Desligar todos os dias às 23h
#    community.windows.win_scheduled_task:
#      name: Desligar às 23h
#      description: Desligar o computador todos os dias às 23h
#      actions:
#      - path: shutdown.exe
#        arguments: /s /f
#      triggers:
#      - type: daily
#        start_boundary: '2022-05-06T23:00:00'
#      username: SYSTEM
#      run_level: highest
#      state: present
#      enabled: yes
#  - name: Remover a tarefa de desligamento antiga
#    community.windows.win_scheduled_task:
#      name: desligamento 2300
#  - name: install the Win32-OpenSSH service
#    win_chocolatey:
#     name: openssh
#     package_params: /SSHServerFeature
#     state: present

