---
- name: lab6
  hosts: all 
  tasks:
    - name: Copiar desinstalador do plugin do flash player 
      import_tasks: plugin_flash_player.yaml
      when: ansible_facts['product_name'] == "OptiPlex 780" 

