---
- name: Main Execution Playbook
  hosts: '{{ local }}'
  serial: '25%'  
  ignore_unreachable: true
  roles:
    - smd 
    - hosts_file
    - maintenance
  gather_facts: yes

  pre_tasks:
    - name: Choose High Performance energy power plan for 7010, 780, m3209, 5400AIO
      community.windows.win_power_plan:
        name: Alto desempenho 
      when: 
      - ansible_facts['product_name'] != "DB85PRO"

    - name: Choose high power plan for HP Compaq 6005
      community.windows.win_power_plan:
        name: Alto desempenho 
      when: ansible_facts['product_name'] == "HP Compaq 6005 Pro SFF PC" 

    - name: Ensure schedule task 'Shutdown everyday at 23:00' is present
      community.windows.win_scheduled_task:
        name: Desligar às 23h
        description: Desligar todos os dias às 23h
        actions:
        - path: shutdown.exe
          arguments: /s /f
        triggers:
        - type: daily
          start_boundary: '2022-05-06T23:00:00'
        username: SYSTEM
        run_level: highest
        wake_to_run: yes
        state: present
        enabled: yes

  tasks:
    - name: Run maintenance tasks
      include_role: 
        name: maintenance

  post_tasks:
    - name: Choose Balanced energy power plan for 7010, 780, m3209, 5400AIO
      community.windows.win_power_plan:
        name: equilibrado 
      when: 
      - ansible_facts['product_name'] != "DB85PRO"

    - name: Set autologon for user aluno
      community.windows.win_auto_logon:
        username: aluno
        password: aluno
 

