---
- name: Tomcat 9 installation on Avell Notebooks with Linux Ubuntu 22.0 #https://www.youtube.com/watch?v=1-53yf7q8eQ
  hosts: avell 
  vars:
    download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.tar.gz
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Download Open JDK
      become: yes
      apt:
        name: openjdk-11-jre-headless
        update-cache: yes
        state: present

    - name: Validade if Java is available
      shell: |
        java -version

    - name: Create the Tomcat group
      become: yes
      group:
        name: tomcat
        state: present

    - name: Create the Tomcat user
      become: yes
      user:
        name: tomcat
        state: present
    
    - name: Create tomcat directory 
      become: yes
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        owner: tomcat
        group: tomcat
      
    - name: Download Tomcat
      become: yes
      unarchive:
        src: '{{ download_url }}'
        dest: /opt/tomcat
        mode: 0755
        remote_src: yes
        group: tomcat
        owner: tomcat

    - name: Create a service file
      become: yes
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 
          After=network.target

          [Service]
          Type=forking

          User=tomcat
          Group=tomcat

          Environment="JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64"
          Environment="JAVA_OPTS=-Djava.security.egd=file:///dev/urandom -Djava.awt.headless=true"
          Environment="CATALINA_BASE=/opt/tomcat"
          Environment="CATALINA_HOME=/opt/tomcat"
          Environment="CATALINA_PID=/opt/tomcat/temp/tomcat.pid"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target
    
    - name: Reload the systemd to re-read configurations
      become: yes
      systemd:
        daemon_reload: yes

    - name: Enable the Tomcat service and ExecStart
      become: yes
      systemd:
        name: tomcat
        enabled: yes
        state: started

    - name: Connect to tomcat server on port 8080 and check status 200 - Try 5 times
      tags: test
      uri:
        url: http://localhost:8080
      register: result
      until: "result.status == 200"
      retries: 5
      delay: 10
  
    - name: Adjust firewall
      become: yes
      ufw:
        rule: allow 
        port: '8080'
        proto: tcp
