- name: Ensure Python and Pycharm are installed
  win_chocolatey:
    name:
      - python
      - pycharm-community
    state: latest
- name: Ensure firewall rule for Pycharm is enabled
  win_firewall_rule:
    name: PyCharm
    program: '{{ pycharm_exec_path }}'
    direction: in
    action: allow
    state: present
    enabled: yes
