---
- name: Download P5 JS
  win_get_url:
    url: https://github.com/processing/p5.js/releases/download/v1.5.0/p5.zip
    dest: "{{ downloads }}"

- name: Unzip P5 JS
  win_unzip:
    src: "{{ downloads }}/p5.zip"
    dest: "{{ aplicativos }}/p5"
    delete_archive: yes
