appdata: 'c:\Users\aluno\appdata\Roaming\Microsoft\Windows\Start Menu\Programs\Startup'
user_temp_folder: 'C:\Users\aluno\AppData\Local\Temp'
downloads: 'c:\Users\aluno\Downloads'
aluno_documents_folder: 'c:\Users\aluno\Documents'  
aluno_desktop: 'c:\Users\aluno\Desktop'
aplicativos: 'c:\Aplicativos'

