---
- name: Escolher o plano de energia equilibrado para 7010, 780, m3209, 5400AIO
  community.windows.win_power_plan:
    name: alto desempenho #381b4222-f694-41f0-9685-ff5bb260df2e
  when: 
  - ansible_facts['product_name'] != "DB85PRO"
- name: Escolher o plano Alto desempenho para os HP Compaq
  community.windows.win_power_plan:
    name: Alto desempenho
  when: ansible_facts['product_name'] == "HP Compaq 6005 Pro SFF PC" 

- name: Desligar todos os dias às 23h
  community.windows.win_scheduled_task:
    name: Desligar às 23h
    description: Desligar todos os dias às 23h
    actions:
    - path: shutdown.exe
      arguments: /s /f
    triggers:
    - type: daily
      start_boundary: '2022-05-06T23:00:00'
    username: SYSTEM
    run_level: highest
    wake_to_run: yes
    state: present
    enabled: yes
- name: Remover a tarefa de desligamento antiga
  community.windows.win_scheduled_task:
    name: 
    - desligamento 2300
    - Desligamento automático
    - desligamento auto
    state: absent
#
