downloads: 'c:\Users\aluno\Downloads'
p5_url: 'https://github.com/processing/p5.js/releases/download/v1.5.0/p5.zip'
aplicativos: 'c:\Aplicativos'
processing_url: 'https://github.com/processing/processing4/releases/download/processing-1289-4.1.1/processing-4.1.1-windows-x64.zip'
processing_zip_file: 'processing-4.1.1-windows-x64.zip'
processing_exec_file: 'C:\Program Files\processing-4.1.1\processing.exe'
