---
- name: Remove old user files and directories
  hosts: lab3 
  vars:
    directories: ['/Users/aluno/Desktop']
  tasks:
    - name: Collect directories and files
      tags: always
      find:
        paths: "{{ directories }}" 
        recurse: true 
        file_type: any 
      register: collected
    
    - name: show files and directories
      tags: always
      debug:
        var: collected
    
    - name: remove files and directories
      tags: never, delete
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ collected.files }}"
