---
- name: Main Execution Playbook
  hosts: '{{ local }}'
  roles:
    - faixas
    - energia
    - powerbi
    - hosts_file
  tasks:
    - name: Install windows Exporter 
      import_tasks: windows_exporter.yml
      tags: never, windows_exporter 

    - name: Install node_exporter 
      import_tasks: node_exporter.yml
      tags: never, node_exporter 
  
    - name: reboot 
      win_reboot:
        reboot_timeout: 3600
        msg: "Restarting to apply updates"
      tags: never, reboot

    - name: Install Windows Updates
      import_tasks: win_updates.yaml
      tags: never, win_updates

    - name: Set autologon for user aluno
      community.windows.win_auto_logon:
        username: aluno
        password: aluno
      tags: never, aluno_auto_logon
    
    - name: Trash Bin clean
      win_shell: rd /s /q %systemdrive%\$Recycle.bin
      args: 
        executable: cmd
      tags: never,bin
    
    - name: NVDA
      import_tasks: nvda.yaml
      tags: never,nvda
   
    - name: SQLServer
      import_tasks: sqlserver.yaml
      tags: never,sqlserver
