- name: assert
  hosts: 10.102.225.228

  tasks:
  - name: check if memory is between 7000 and 9000 MB
    assert:
      that:
        - ansible_memtotal_mb | int >= 7000
        - ansible_memtotal_mb | int <= 9000
      fail_msg: "Memory is {{ ansible_memtotal_mb }}MB"
    register: result
    changed_when:
      - result.evaluated_to is defined
      - result.evaluated_to == False
    failed_when: False
