---
- name: Media Week install playbook 
  hosts: "{{ local }}"
  tasks:
    - name: Install apps from chocolatey repo
      win_chocolatey:
        name: "{{ item }}"
        state: latest
      loop:
        - flutter
        - vscode
