---
- name: Media Week install playbook 
  hosts: "{{ local }}"
  tasks:
    - name: Install apps from chocolatey repo
      win_chocolatey:
        name: "{{ item }}"
        state: latest
      loop:
        - flutter
        - vscode
        - git
    - name: add flutter install folder to system path
      win_path:
        elements: C:\tools\flutter\bin
    - name: Reboot after changing system path
      win_reboot: 
    - name: Add an git exception for c:\tools\flutter directory
      win_command: "{{ item }}"
      loop: 
        - git config --global --add safe.directory C:/tools/flutter
        - flutter doctor --android-licenses


# atalho do android studio
# abrir portas para o android studio virtual device manager
