---
- name: Copy and unzip content to Desktop
  hosts: lab1 
  vars:
    aluno_download: c:\Users\aluno\Downloads

  tasks:
    - name: Copy aseprite zip file to the hosts
      win_copy:
        src: aseprite.zip #https://drive.google.com/file/d/14-_rblzRIX9Z0q2mjoPnk8eLFt0f3sNP/view?usp=drivesdk
        dest: "{{ aluno_download }}"
    - name: 
      win_unzip:
        src: c:\Users\aluno\Downloads\aseprite.zip 
        dest: c:\Users\aluno\Desktop
