---
- name: Install Postgresql 15
  hosts: 10.102.227.142

  tasks:
    - name: Install:q
      win_chocolatey:
        name: postgresql15
       #install_args: "--params '/Username:postgres /Password:ufc123'"
        package_params: "'/Username:postgres /Password:ufc123'"
        state: present 
      tags:
        - install
    - name: Change postgres password
      community.postgresql.postgresql_user:
        name: postgres
        db: postgres
        comment: Usuário para uso didático
      tags: 
        - password
