- name: Create user sqlserver
  win_user:
    name: sqlserver
    password: ufc20231
    state: present
    groups:
      - Administradores
  tags: never,sqlserver_create_user

- name: Copy install files 
  win_copy:
    src: sqlserver/
    dest: c:\Users\sqlserver\Downloads
  tags: never,sqlserver_install_files
