# Playbook para transferir arquivos
#
- name: Playbook de transferir arquivos
  hosts: all
  tasks:

  - name: Atualizar o arquivo resolv.conf
    become: true
    copy:
            src: resolv.conf
            dest: c:\
