- name: Select a style to wallpaper
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: WallpaperStyle
    data: 2
    type: string

# try this: https://github.com/crombeen/ansible/blob/master/desktop.yml
# - path: HKCU:\Control Panel\Desktop
#       name: WallpaperStyle
#       data: 10
#       type: string