---
- name: Configure WinRM for updates
  ansible.windows.win_service:
    name: WinRM
    start_mode: delayed

- name: Pre Updates Check
  ansible.windows.win_updates:
    category_names:
      - Application
      - Connectors
      - SecurityUpdates
      - CriticalUpdates
      - QualityUpdates
      - UpdateRollups
      - FeaturePacks
      - ServicePacks
      - Drivers
      - DeveloperKits
      - DefinitionUpdates
      - Updates
      - Windows 11
      - Microsoft Defender Antivirus
      - Windows 10 LTSB
      - Windows 10, version 1903 and later
      - Guidance
      - Tools
    state: searched
    log_path: C:\Windows\Temp\Pre-AllUpdatesFound.txt

- name: First update run
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - Updates
    reboot: yes 
    state: installed
    log_path: C:\Windows\Temp\ansible_updates_first_run.txt

#- name: First update run reboot
#  win_reboot:
#    reboot_timeout: 3600

- name: Second update run
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - Updates
    reboot: yes
    state: installed
    log_path: C:\Windows\Temp\ansible_updates_second_run.txt

#- name: Second update run reboot
#  win_reboot:
#    reboot_timeout: 3600

- name: Third update run
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - Updates
    reboot: yes
    state: installed
    log_path: C:\Windows\Temp\ansible_updates_third_run.txt

#- name: Third update run reboot
#  win_reboot:
#    reboot_timeout: 3600

- name: Post Update Check
  ansible.windows.win_updates:
    category_names:
      - Application
      - Connectors
      - CriticalUpdates
      - DefinitionUpdates
      - DeveloperKits
      - FeaturePacks
      - Guidance
      - SecurityUpdates
      - ServicePacks
      - Tools
      - UpdateRollups
      - Updates
    state: searched
    log_path: C:\Windows\Temp\Post-AllUpdatesFound.txt

- name: Set WinRM back to standard settings
  ansible.windows.win_service:
    name: WinRM
    start_mode: auto

